config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :votes
  resources :posts

    root to: "posts#index"

    mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  after_commit -> { VotesrelayJob.perform_later(self) }
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Sua notícia foi criada com sucesso.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Você excluiu uma notícia.' }
    end
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:contents, :upvote, :downvote)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_posts, only: [:update]

    def update
      if params[:upvote].present?
        @posts.increment(:upvote)
        @posts.save
      render json: @posts
      elsif params[:downvote].present?
        @posts.decrement(:downvote)
        @posts.save
      render json: @posts
      end
    end


  private

    def set_posts
      @posts = Post.find(params[:id])
    end

    def broadcast(votes)
      VotesChannel.broadcast_to votes, @Posts
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div align="right">
      <% if user_signed_in?%>

      Usuario:  <%=current_user.email%>
    <%end%>
    <% if user_signed_in? %>
  <li>
  <%= link_to('Sair', destroy_user_session_path, method: :delete) %>
  </li>
<% end %>
  </div>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  </div>
  <div class="field" align="center">
    <%= form.text_area :contents %>
  </div>

  <div class="actions" align="center">
    <%= form.submit "Enviar notícia" %>
  </div>
<% end %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="content">
<table>
  <thead>
  </thead>

  <tbody>

    <% @posts.each do |post| %>
      <tr>
        <br>

        <td><button class="downvote" data-id=<%="#{post.id}"%>><%=post.downvote%></button></td>
        <td><hr size="30"></td>
        <td><font face="arial" size="3"><%= post.contents %></font></td>
        <td><hr size="30"></td>
        <td><button class="upvote" data-id=<%="#{post.id}"%>><%=post.upvote%></button></td>
        <td><%= link_to 'Excluir', post, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>


<br>
<div align="center"><%= link_to 'Nova notícia', new_post_path %></div>

app/views/posts/new.html.erb
<div align="center"><h1>Qual sua notícia?</h1></div>


<%= render 'form', post: @post %>

<div align="center"><%= link_to 'voltar', posts_path %></div>

app/views/posts/show.html.erb
<h1></h1>